export enum ExpressCompany {
    STKD = "中通快递",
    ZTKD = "申通快递",
    TTKD = "天天快递",
    YTSY = "圆通速递",
    ZGYZ = "中国邮政",
    YDKD = "韵达快递",
    BSKD = "百世快递",
    SFSY = "顺丰速运",
    QFKD = "全峰快递",
    KJKD = "快捷快递",
    GTKD = "国通快递",
    YSKD = "优速快递",
    RRSKD = "日日顺物流",
    BDKD = "德邦快递",
    OTHER = "其他",
    ANWL = "安能物流",
    WXWL = "万象物流",
    JYWL = "佳怡物流",
    JJWL = "佳吉物流"
}